python: "2.7"

matrix:
  include:
    - name: "Linux :: Python2.7"
      os: linux
      language: python
    - name: "OSX :: Python 2.7"
      os: osx
      language: generic

  before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi

env:
  global:
    - PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages/:$PYTHONPATH
    - PATH=/home/travis/.local/bin/:$PATH

install:
  - python framework/setup.py install --user --prefix=

script:
  - python framework/setup.py distclean
