#!/usr/bin/env python
import os
import subprocess


def amend_readme():
    os.remove(".commit")

    content = """\
<!-- Auto generated badges -->
[![PyPI version](https://img.shields.io/pypi/v/template.svg)](https://pypi.org/project/template)
![Python version](https://img.shields.io/badge/Python-2.7-brightgreen.svg)
![Coding style](https://img.shields.io/badge/style-PEP8-blue.svg)
[![Build status](https://travis-ci.com/grand-mother/template.svg?branch=master)](https://travis-ci.com/grand-mother/template)

"""
    with open("docs/README.md", "r") as f:
        content += f.read()

    with open("README.md", "w") as f:
        f.write(content)

    def system(command):
        p = subprocess.Popen(
            command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p.communicate()

    system("git add README.md")
    system("git commit --amend -C HEAD --no-verify")


if __name__ == "__main__":
    if os.path.exists(".commit"):
        amend_readme()
